### ISSUE TITLE
"like" button has white background

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#28]
The  button containing the font-awesome "fa-heart" icon has a white background, which looks wrong for responses, since the response list has a light grey background.

I think the issue is the following CSS rule:

(I can't blame a file since I'm looking at concatenated files so everything is in `app.css`).

```css
.ww-score button {
    background-color: #fff;
    cursor: pointer;
}
```
